import { TrainRoute } from '../types';

/**
 * Données indicative Madarail — tarifs exemples (à ajuster selon grille officielle).
 * Capacités : Train voyageur 88 ; Micheline 20 ; Trans Lémurie 52.
 */
export const mockRoutes: TrainRoute[] = [
  /* --- Train voyageur : Moramanga – Ambila Lemaitso (TCE) — 88 places --- */
  {
    id: 'tv-mor-amb-1',
    name: 'Moramanga – Ambila Lemaitso',
    serviceName: 'Train voyageur',
    operatingDays: 'Dimanche, Jeudi',
    departure: 'Moramanga',
    arrival: 'Ambila Lemaitso',
    category: 'MOR',
    classe: '2ème classe',
    price: 48_000,
    seatsAvailable: 88,
    trainNumber: 'TV-MOR-TCE',
    departureTime: '07:00',
    arrivalTime: '16:00',
    duration: '9h',
  },
  {
    id: 'tv-amb-mor-1',
    name: 'Ambila Lemaitso – Moramanga',
    serviceName: 'Train voyageur',
    operatingDays: 'Mardi, Samedi',
    departure: 'Ambila Lemaitso',
    arrival: 'Moramanga',
    category: 'MOR',
    classe: '2ème classe',
    price: 48_000,
    seatsAvailable: 88,
    trainNumber: 'TV-MOR-TCE',
    departureTime: '07:00',
    arrivalTime: '16:00',
    duration: '9h',
  },

  /* --- La Micheline « Viko Viko » — 20 places max --- */
  {
    id: 'viko-tce-mj',
    name: 'Antananarivo – Manjakandriana',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Manjakandriana',
    category: 'TCE',
    classe: '2ème classe',
    price: 8_000,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TCE',
    departureTime: '06:00',
    arrivalTime: '07:30',
    duration: '1h30',
  },
  {
    id: 'viko-tce-and',
    name: 'Antananarivo – Andasibe',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Andasibe',
    category: 'TCE',
    classe: '2ème classe',
    price: 22_000,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TCE',
    departureTime: '06:00',
    arrivalTime: '10:00',
    duration: '4h00',
  },
  {
    id: 'viko-tce-toa',
    name: 'Antananarivo – Toamasina',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Toamasina',
    category: 'TCE',
    classe: '2ème classe',
    price: 45_000,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TCE',
    departureTime: '06:00',
    arrivalTime: '16:00',
    duration: '10h00',
  },
  {
    id: 'viko-ta-beh',
    name: 'Antananarivo – Behenjy',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Behenjy',
    category: 'TA',
    classe: '2ème classe',
    price: 7_500,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TA',
    departureTime: '06:00',
    arrivalTime: '07:00',
    duration: '1h00',
  },
  {
    id: 'viko-ta-amb',
    name: 'Antananarivo – Ambatolampy',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Ambatolampy',
    category: 'TA',
    classe: '2ème classe',
    price: 14_000,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TA',
    departureTime: '06:00',
    arrivalTime: '08:00',
    duration: '2h00',
  },
  {
    id: 'viko-ta-ants',
    name: 'Antananarivo – Antsirabe',
    serviceName: 'Micheline « Viko Viko »',
    departure: 'Antananarivo',
    arrival: 'Antsirabe',
    category: 'TA',
    classe: '2ème classe',
    price: 28_000,
    seatsAvailable: 20,
    trainNumber: 'VIKO-TA',
    departureTime: '06:00',
    arrivalTime: '10:30',
    duration: '4h30',
  },

  /* --- Trans Lémurie Express — 52 places max --- */
  {
    id: 'tle-tce-mj',
    name: 'Antananarivo – Manjakandriana',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Manjakandriana',
    category: 'TCE',
    classe: '2ème classe',
    price: 10_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TCE',
    departureTime: '06:00',
    arrivalTime: '08:30',
    duration: '2h30',
  },
  {
    id: 'tle-tce-and',
    name: 'Antananarivo – Andasibe',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Andasibe',
    category: 'TCE',
    classe: '2ème classe',
    price: 26_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TCE',
    departureTime: '06:00',
    arrivalTime: '11:00',
    duration: '5h00',
  },
  {
    id: 'tle-tce-toa',
    name: 'Antananarivo – Toamasina',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Toamasina',
    category: 'TCE',
    classe: '2ème classe',
    price: 52_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TCE',
    departureTime: '06:00',
    arrivalTime: '18:00',
    duration: '12h00',
  },
  {
    id: 'tle-ta-beh',
    name: 'Antananarivo – Behenjy',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Behenjy',
    category: 'TA',
    classe: '2ème classe',
    price: 9_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TA',
    departureTime: '06:00',
    arrivalTime: '08:00',
    duration: '2h00',
  },
  {
    id: 'tle-ta-amb',
    name: 'Antananarivo – Ambatolampy',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Ambatolampy',
    category: 'TA',
    classe: '2ème classe',
    price: 16_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TA',
    departureTime: '06:00',
    arrivalTime: '09:00',
    duration: '3h00',
  },
  {
    id: 'tle-ta-ants',
    name: 'Antananarivo – Antsirabe',
    serviceName: 'Trans Lémurie Express',
    departure: 'Antananarivo',
    arrival: 'Antsirabe',
    category: 'TA',
    classe: '2ème classe',
    price: 32_000,
    seatsAvailable: 52,
    trainNumber: 'TLE-TA',
    departureTime: '06:00',
    arrivalTime: '11:00',
    duration: '5h00',
  },
];
