import { TrainRoute } from '../types';

export const mockRoutes: TrainRoute[] = [
  {
    id: '1',
    name: 'Fianarantsoa - Manakara',
    departure: 'Fianarantsoa',
    arrival: 'Manakara',
    category: 'FCE',
    classe: '1ère classe',
    price: 60000,
    seatsAvailable: 40,
    trainNumber: 'FCE-001',
    departureTime: '07:00',
    arrivalTime: '19:00',
    duration: '12h',
  },
  {
    id: '2',
    name: 'Fianarantsoa - Manakara',
    departure: 'Fianarantsoa',
    arrival: 'Manakara',
    category: 'FCE',
    classe: '2ème classe',
    price: 35000,
    seatsAvailable: 80,
    trainNumber: 'FCE-001',
    departureTime: '07:00',
    arrivalTime: '19:00',
    duration: '12h',
  },
  {
    id: '3',
    name: 'Fianarantsoa - Manakara',
    departure: 'Fianarantsoa',
    arrival: 'Manakara',
    category: 'FCE',
    classe: '3ème classe',
    price: 20000,
    seatsAvailable: 120,
    trainNumber: 'FCE-001',
    departureTime: '07:00',
    arrivalTime: '19:00',
    duration: '12h',
  },
  {
    id: '4',
    name: 'Manakara - Fianarantsoa',
    departure: 'Manakara',
    arrival: 'Fianarantsoa',
    category: 'FCE',
    classe: '1ère classe',
    price: 60000,
    seatsAvailable: 40,
    trainNumber: 'FCE-002',
    departureTime: '07:00',
    arrivalTime: '19:00',
    duration: '12h',
  },
  {
    id: '5',
    name: 'Manakara - Fianarantsoa',
    departure: 'Manakara',
    arrival: 'Fianarantsoa',
    category: 'FCE',
    classe: '2ème classe',
    price: 35000,
    seatsAvailable: 80,
    trainNumber: 'FCE-002',
    departureTime: '07:00',
    arrivalTime: '19:00',
    duration: '12h',
  },
  {
    id: '6',
    name: 'Antananarivo - Antsirabe',
    departure: 'Antananarivo',
    arrival: 'Antsirabe',
    category: 'TCE',
    classe: '1ère classe',
    price: 25000,
    seatsAvailable: 50,
    trainNumber: 'TCE-001',
    departureTime: '06:30',
    arrivalTime: '10:30',
    duration: '4h',
  },
  {
    id: '7',
    name: 'Antananarivo - Antsirabe',
    departure: 'Antananarivo',
    arrival: 'Antsirabe',
    category: 'TCE',
    classe: '2ème classe',
    price: 15000,
    seatsAvailable: 100,
    trainNumber: 'TCE-001',
    departureTime: '06:30',
    arrivalTime: '10:30',
    duration: '4h',
  },
  {
    id: '8',
    name: 'Antsirabe - Antananarivo',
    departure: 'Antsirabe',
    arrival: 'Antananarivo',
    category: 'TCE',
    classe: '1ère classe',
    price: 25000,
    seatsAvailable: 50,
    trainNumber: 'TCE-002',
    departureTime: '14:00',
    arrivalTime: '18:00',
    duration: '4h',
  },
  {
    id: '9',
    name: 'Antananarivo - Ambatondrazaka',
    departure: 'Antananarivo',
    arrival: 'Ambatondrazaka',
    category: 'MLA',
    classe: '1ère classe',
    price: 40000,
    seatsAvailable: 30,
    trainNumber: 'MLA-001',
    departureTime: '06:00',
    arrivalTime: '14:00',
    duration: '8h',
  },
  {
    id: '10',
    name: 'Antananarivo - Ambatondrazaka',
    departure: 'Antananarivo',
    arrival: 'Ambatondrazaka',
    category: 'MLA',
    classe: '2ème classe',
    price: 25000,
    seatsAvailable: 60,
    trainNumber: 'MLA-001',
    departureTime: '06:00',
    arrivalTime: '14:00',
    duration: '8h',
  },
  {
    id: '11',
    name: 'Moramanga - Lac Alaotra',
    departure: 'Moramanga',
    arrival: 'Ambatondrazaka',
    category: 'MLA',
    classe: '2ème classe',
    price: 18000,
    seatsAvailable: 80,
    trainNumber: 'MLA-003',
    departureTime: '08:00',
    arrivalTime: '13:00',
    duration: '5h',
  },
  {
    id: '12',
    name: 'Antananarivo - Toamasina',
    departure: 'Antananarivo',
    arrival: 'Toamasina',
    category: 'TCE-Est',
    classe: '1ère classe',
    price: 55000,
    seatsAvailable: 35,
    trainNumber: 'TCE-E01',
    departureTime: '05:30',
    arrivalTime: '15:30',
    duration: '10h',
  },
  {
    id: '13',
    name: 'Antananarivo - Toamasina',
    departure: 'Antananarivo',
    arrival: 'Toamasina',
    category: 'TCE-Est',
    classe: '2ème classe',
    price: 35000,
    seatsAvailable: 70,
    trainNumber: 'TCE-E01',
    departureTime: '05:30',
    arrivalTime: '15:30',
    duration: '10h',
  },
];
